// assignment_3/src/screens/Profile.tsx
import { Button, message, Form, Input } from "antd"
import _ from "lodash"
import { useEffect, useState } from "react"
import { useDispatch, useSelector } from "react-redux"
import { User } from "../model/model"
import { Dispatch, State } from "../store"
import { newGame, scores, logout } from "../thunks"

export const Profile = () => {
    const gameState = useSelector((s: State) => s.game)
    console.log(gameState);

    const updateUser = async (values: any) => {
        const response = await fetch(`http://localhost:9090/users/${gameState.player?.id}?token=${gameState.token}`, { method: 'PATCH', body: JSON.stringify(values), headers: { 'Accept': 'application/json', 'Content-Type': 'application/json' } })
        if (response.ok) {
            message.success("Info changd")
        } else {
            return Promise.reject(response.statusText)
        }
    }

    const dispatch: Dispatch = useDispatch()
    return (
        <>
            <Button onClick={() => dispatch(logout(gameState.token || ""))}>Logout</Button>
            <h1>Hello, {gameState.player?.username}</h1>
            <h3>Wanna play</h3>
            <Button onClick={() => (dispatch(newGame(gameState.token || "", gameState.player || { id: -1, password: "", username: "" })))}>Play</Button>
            <Button onClick={() => (dispatch(scores(gameState.token || "", gameState.player || { id: -1, password: "", username: "" })))}>See Scores</Button>

            <div>
                <Form
                    name="basic"
                    labelCol={{ span: 8 }}
                    wrapperCol={{ span: 16 }}
                    onFinish={updateUser}
                    autoComplete="off"
                >
                    <Form.Item
                        label="New Password"
                        name="password"
                        rules={[{ required: true, message: 'Please input your password!' }]}
                    >
                        <Input.Password />
                    </Form.Item>
                    <Form.Item wrapperCol={{ offset: 8, span: 16 }}>
                        <Button type="primary" htmlType="submit">
                            Submit
                        </Button>
                    </Form.Item>
                </Form>
            </div>
        </>
    )
}

// assignment_4/src/components/Profile.vue
<script lang="ts">
import type { Game, User } from '@/model/model';
import type { PropType } from 'vue';
import * as api from '@/api'

export default {
    data() {
        return {
            password: '',
            message: ""
        }
    },
    props: {
        player: {
            type: Object as PropType<User>,
            require: true
        },
        token: {
            type: String as PropType<string>,
            required: true
        }
    },
    emits: {
        score(_: Game[]) {
            return true
        },
        play(_: Game) {
            return true
        },
        login() {
            return true
        }
    },
    methods: {
        async playButton() {
            const game = await api.newGame(this.token)
            this.$emit('play', game)
        },
        async scoresButton() {
            console.log(this.player, this.token);

            const games = await api.getGames(this.token)
            this.$emit('score', games)
        },
        async onFinish() {
            const response = await fetch(`http://localhost:9090/users/${this.player?.id}?token=${this.token}`, { method: 'PATCH', body: JSON.stringify({ password: this.password }), headers: { 'Accept': 'application/json', 'Content-Type': 'application/json' } })
            if (response.ok) {
                this.message = "Password changed"
            } else {
                this.message = "Something went wrong"
                return Promise.reject(response.statusText)
            }
        },
        async logout() {
            const log = await api.logout(this.token)
            if (log) {
                this.$emit('login')
            }
        }
    }
}
</script>

<template>
    <button @click="logout">Logout</button>
    <br>
    <h1>Welcome {{ player?.username }}</h1>
    <button @click="playButton">Play</button>
    <button @click="scoresButton">See Scores</button>
    <br>
    <br>
    <form @submit.prevent="onFinish">
        <label>New Password:</label>
        <input type="password" required v-model="password">
        <button @click.prevent="onFinish">Change Password</button>
        <br>
        <label>{{ message }}</label>
    </form>
</template>
