// assignment_4/src/components/PlayGame.vue
<script lang="ts">
import { type Board, type Tile, type Position, create, move, type Game, type User } from '@/model/model';
import { ref, type PropType } from 'vue';
import * as api from '@/api'

const initBoard: Board = create(5, 4)
const board = ref(initBoard)

export default {
    data() {
        return {
            tiless: [] as Position[],
            board
        }
    },
    props: {
        game: {
            type: Object as PropType<Game>,
            require: true
        },
        token: {
            type: String as PropType<string>,
            required: true
        },
        player: {
            type: Object as PropType<User>,
            required: true
        }
    },
    emits: {
        profile(_: string, user: User) {
            return true
        }
    },
    methods: {
        tiles(row: number): Tile[] {
            //get board from model
            return this.board.tiles.filter(x => {
                return x.position.row == row
            })
        },
        makeMove(tile: Position) {
            this.tiless.push(tile)
            console.log(this.tiless);

            if (this.tiless.length == 2) {
                this.board = move(this.board, this.tiless[0], this.tiless[1])
                this.tiless = []
            }
        },
        async endGame() {
            if (this.game) {
                this.game.score = this.board.score
                await api.updateGame(this.game, this.token)
                this.$emit('profile', this.token, this.player)
            }
        }
    }
}
</script>

<template>
    <h2>Score {{ board.score }}</h2>
    <table>
        <tr>
            <td v-for='tile in tiles(1)'><button @click='makeMove(tile.position)'>{{ tile.piece }}</button></td>
        </tr>
        <tr>
            <td v-for='tile in tiles(2)'><button @click='makeMove(tile.position)'>{{ tile.piece }}</button></td>
        </tr>
        <tr>
            <td v-for='tile in tiles(3)'><button @click='makeMove(tile.position)'>{{ tile.piece }}</button></td>
        </tr>
        <tr>
            <td v-for='tile in tiles(4)'><button @click='makeMove(tile.position)'>{{ tile.piece }}</button></td>
        </tr>
    </table>
    <br>
    <button @click="endGame">End Game</button>
</template>

// assignment_3/src/screens/PlayGame.tsx
import { Avatar, Button } from "antd"
import _ from "lodash"
import { useEffect, useState } from "react"
import { useDispatch, useSelector } from "react-redux"
import { Board, create, move, Tile } from "../model/model"
import { Dispatch, State } from "../store"
import { updateGame } from "../thunks"

export const PlayGame = () => {
    const [selectedTile, setSelectedTile] = useState<Tile>({ piece: -1, position: { row: -1, col: -1 } })
    const [board, setBoard] = useState<Board>({ tiles: [], width: 0, height: 0, score: 0 })
    const gameState = useSelector((s: State) => s.game)
    const dispatch: Dispatch = useDispatch()

    useEffect(() => {
        setBoard(create(4, 4))
    }, [])

    const onSelectTile = (tile: Tile) => {
        console.log(tile);

        if (selectedTile.piece != -1) {
            console.log(selectedTile);

            let s = move(board, tile.position, selectedTile.position)
            console.log(s);

            setBoard(s)
            setSelectedTile({ piece: -1, position: { row: -1, col: -1 } })
        } else {
            setSelectedTile(tile)
        }
    }

    const endGame = () => {
        let gameM = _.cloneDeep(gameState)
        if (gameM.game) {
            gameM.game.score = board.score
            console.log(gameState);

            dispatch(updateGame(gameM.game, (gameState.token || ""), gameM.player || { id: -1, username: "", password: "" }))
        }
    }

    return (
        <>
            <h1>Score {board.score}</h1>
            <table>
                <tbody>
                    <tr>
                        {_.map(board.tiles, (c: Tile) => {
                            if (c.position.row == 0) {
                                return (<td key={c.position.col + "" + c.position.row}>
                                    <Button onClick={() => onSelectTile(c)} disabled={c == selectedTile}>{c.piece}</Button></td>)
                            }
                        })}
                    </tr>
                    <tr>
                        {_.map(board.tiles, (c: Tile) => {
                            if (c.position.row == 1) {
                                return (<td key={c.position.col + "" + c.position.row}>
                                    <Button onClick={() => onSelectTile(c)} disabled={c == selectedTile}>{c.piece}</Button></td>)
                            }
                        })}
                    </tr>
                    <tr>
                        {_.map(board.tiles, (c: Tile) => {
                            if (c.position.row == 2) {
                                return (<td key={c.position.col + "" + c.position.row}>
                                    <Button onClick={() => onSelectTile(c)} disabled={c == selectedTile}>{c.piece}</Button></td>)
                            }
                        })}
                    </tr>
                    <tr>
                        {_.map(board.tiles, (c: Tile) => {
                            if (c.position.row == 3) {
                                return (<td key={c.position.col + "" + c.position.row}>
                                    <Button onClick={() => onSelectTile(c)} disabled={c == selectedTile}>{c.piece}</Button></td>)
                            }
                        })}
                    </tr>

                </tbody>
            </table>
            <Button onClick={endGame}>End Game</Button>
        </>
    )
}
